<h1 style = "color : Brown">NumPy</h1>

- __NumPy__ is a Python library.
- It is used for working with arrays.
- It is short for "Numerical Python".
- It is used for computation and processing of single and multi dimensional array of elements.
- Smaller memory consumption and better runtime behavior.

Numpy Official Documentation:[https://numpy.org/doc/stable/user/index.html#user](https://numpy.org/doc/stable/user/index.html#user)

In [ ]:
# To install the library

!pip install numpy


## Basic Operations

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [5]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
type(b)

numpy.ndarray

In [7]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#Get Dimensions of a numpy array
a.ndim

1

In [9]:
#Get Dimensions of a numpy array
b.ndim

2

In [10]:
c.ndim

2

## Why Use NumPy?

- In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to __50x__ faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#Get a shape of a numpy array(how many rows and column are present)
b.shape

(2, 3)

In [14]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
c.shape

(3, 3)

In [16]:
a

array([1., 2., 3.])

In [17]:
a.dtype

dtype('float64')

In [18]:
a_int = np.array([1.1,2.1,3.4])
print(a_int)

[1.1 2.1 3.4]


In [19]:
a_int.dtype

dtype('float64')

## Accessing/Changing specific elements, rows & columns etc.

In [20]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a.ndim

2

In [22]:
#Get a specific element [r,c]
a[0,3]

np.int64(4)

In [23]:
a[1,0]

np.int64(8)

In [24]:
a[1,5]

np.int64(13)

In [25]:
#Get a specific row from a numpy array
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
#Get a specific column from a numpy array

a[:,0]

array([1, 8])

In [27]:
#Get a specific column from a numpy array
a[:,0]

array([1, 8])

In [28]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [29]:
#numpy arrays are mutable meaning their data can be changed
a[0,3] = 40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
#Change the 5th column in 1st row to 50
a[0,4] = 50

In [31]:
a

array([[ 1,  2,  3, 40, 50,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

## Zeros/Ones method in NumPy

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [36]:
np.full((3,3), 50, dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [37]:
np.full((3,3), 50, dtype='int32')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]], dtype=int32)

In [38]:
np.random.rand(4,4)

array([[0.18806868, 0.26575281, 0.03978804, 0.08726276],
       [0.80407455, 0.27929321, 0.81444284, 0.26943417],
       [0.43251172, 0.18526805, 0.90968556, 0.31856281],
       [0.23719812, 0.05560279, 0.97135869, 0.72891173]])

In [39]:
np.random.randint(-4,1, size=(3,3))

array([[-3,  0, -2],
       [-1, -4,  0],
       [-4, -1,  0]])

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np

# Create an (nxn) array with all zeros
z = np.zeros((n,n), dtype='int')
print(z)

In [ ]:
# Make the middle row and column all 1s

z[n//2,:] = 1
z[:,n//2] = 1

# Print the final value of z
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


#### Just to help you understand about n//2

In [41]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [42]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [43]:
a[5//2,:]=1

In [44]:
a[:,5//2]=1

In [45]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [10, 20,  1, 40, 50, 60],
       [ 1,  1,  1,  1,  1,  1],
       [11, 21,  1, 41, 51, 61],
       [13, 24,  1, 44, 54, 64]])

In [46]:
a[5//2,:] = 1
print(a)

[[ 1  2  1  4  5  6]
 [10 20  1 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21  1 41 51 61]
 [13 24  1 44 54 64]]


In [47]:
a[:,5//2] = 1
print(a)

[[ 1  2  1  4  5  6]
 [10 20  1 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21  1 41 51 61]
 [13 24  1 44 54 64]]


## Arithmetic Operations with NumPy - Maths + Stats

In [48]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [49]:
a+2

array([3, 4, 5, 6])

In [50]:
#DO it for -, /, *, //, ** - ALmost all the operations are satisfied

a**3

array([ 1,  8, 27, 64])

In [51]:
a

array([1, 2, 3, 4])

In [52]:
a.min()

np.int64(1)

In [53]:
np.min(a)

np.int64(1)

In [54]:
a.max()

np.int64(4)

In [55]:
np.max(a)

np.int64(4)

In [56]:
a.mean()

np.float64(2.5)

In [57]:
np.mean(a)

np.float64(2.5)

In [58]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
np.max(a)

np.int64(8)

In [60]:
a.max()

np.int64(8)

In [61]:
np.min(a)

np.int64(1)

In [62]:
np.mean(a)

np.float64(4.5)

In [63]:
np.sum(a)

np.int64(36)

In [64]:
#axis=1 for rows
np.max(a, axis=1)

array([4, 8])

In [65]:
#axis=0 for columns
np.max(a, axis=0)

array([5, 6, 7, 8])

In [66]:
np.min(a, axis=0)

array([1, 2, 3, 4])

In [67]:
np.min(a, axis=1)

array([1, 5])

In [68]:
np.sum(a, axis=1)

array([10, 26])

In [69]:
np.sum(a, axis=0)

array([ 6,  8, 10, 12])